# Generated by Django 2.1.1 on 2019-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='tel',
            field=models.CharField(max_length=32),
        ),
    ]
